name = "LASindex"
uuid = "f5cc2397-9d3e-5971-afd7-e1f28e1d1eef"
version = "0.1"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
RegionTrees = "dee08c22-ab7f-5625-9660-a9af2021b33f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
RegionTrees = "≥ 0.2.0"
julia = "≥ 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
